package com.gp.GP_backend.domain.user.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

/**
 * Core user entity — represents a registered student on the Covalent platform.
 *
 * <p>
 * Implements {@link UserDetails} so Spring Security can authenticate users
 * directly
 * from this entity without a separate adapter class.
 *
 * <p>
 * <b>ID strategy:</b> Uses UUID (UNIQUEIDENTIFIER in SQL Server) instead of a
 * sequential BIGINT. This prevents enumeration attacks, simplifies future
 * distributed
 * deployments, and avoids leaking record counts in URLs.
 * <br>
 * ⚠️ MIGRATION NOTE: Changing the PK type from BIGINT to UUID requires dropping
 * and
 * re-creating the database. Run {@code database-init.sql} on a fresh
 * {@code GP_db}.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails {

    // ── Primary Key ────────────────────────────────────────────────────────────

    /**
     * UUID primary key. Generated by Hibernate (strategy = UUID).
     * Maps to a UNIQUEIDENTIFIER column in SQL Server.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UNIQUEIDENTIFIER DEFAULT NEWID()")
    private UUID id;

    // ── Authentication Fields ──────────────────────────────────────────────────

    /** Unique email used as the login username. */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /**
     * BCrypt-hashed password.
     * The raw password is NEVER stored — encoding happens in
     * {@link com.gp.GP_backend.domain.user.service.UserService}.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    // ── Profile Fields ─────────────────────────────────────────────────────────

    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;

    /**
     * Optional university student ID (e.g. "20220123"). Must be unique if provided.
     */
    @Column(name = "student_id", unique = true, length = 50)
    private String studentId;

    /** Academic year (1–5). */
    @Column(name = "academic_year")
    private Short academicYear;

    /** Current semester number (1–10). */
    @Column(name = "current_semester")
    private Short currentSemester;

    /** Grade Point Average, stored as DECIMAL(4,2) (e.g. 3.75). */
    @Column(precision = 4, scale = 2)
    private BigDecimal gpa;

    /** Department/major name (e.g. "Computer Science"). */
    @Column(length = 100)
    private String department;

    /**
     * URL of the user's profile picture (stored externally, e.g. S3 / Cloudinary).
     */
    @Column(name = "image_url", length = 512)
    private String imageUrl;

    /** Short biography shown on the user's public profile. */
    @Column(length = 500)
    private String bio;

    // ── Status & Timestamps ────────────────────────────────────────────────────

    /**
     * Soft-delete flag. When {@code false}, the user cannot log in
     * ({@link #isEnabled()} returns {@code false}).
     */
    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    /**
     * Set once at creation; never updated (see {@code updatable = false} on
     * all @Column).
     */
    @Column(name = "created_at", updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Automatically updated by Hibernate on every save/merge. */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ── UserDetails Implementation ─────────────────────────────────────────────

    /**
     * Returns an empty authority list — role-based access control is not yet
     * implemented.
     * When roles are added, return a list of
     * {@link org.springframework.security.core.authority.SimpleGrantedAuthority}.
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of();
    }

    /**
     * Spring Security uses this to verify the submitted password against the stored
     * hash.
     */
    @Override
    public String getPassword() {
        return this.passwordHash;
    }

    /** Spring Security uses email as the unique username. */
    @Override
    public String getUsername() {
        return this.email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * An inactive user ({@link #isActive} = false) cannot authenticate.
     * This is used for soft-deletes / banning without removing the record.
     */
    @Override
    public boolean isEnabled() {
        return Boolean.TRUE.equals(this.isActive);
    }
}