package com.gp.GP_backend.domain.user.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

/**
 * Represents an application user.
 *
 * <p>
 * Implements {@link UserDetails} so that Spring Security can use this entity
 * directly as the authentication principal — no separate "UserDetailsImpl"
 * wrapper needed.
 *
 * <p>
 * <b>Primary key:</b> Uses a client-generated {@link UUID} (JPA strategy
 * {@code UUID}).
 * Hibernate generates the UUID before the INSERT, meaning the ID is available
 * immediately
 * after {@code repository.save()} without a round-trip to the database (unlike
 * IDENTITY).
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails {

    /** Globally unique identifier, generated by Hibernate before insert. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "UNIQUEIDENTIFIER", updatable = false, nullable = false)
    private UUID id;

    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /** BCrypt-hashed password. The raw password is never stored. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "full_name", nullable = false, length = 150)
    private String fullName;

    @Column(name = "student_id", unique = true, length = 50)
    private String studentId;

    /** Academic year 1–5. */
    @Column(name = "academic_year")
    private Integer academicYear;

    /** Semester 1–10 across all academic years. */
    @Column(name = "current_semester")
    private Integer currentSemester;

    @Column(precision = 4, scale = 2)
    private BigDecimal gpa;

    @Column(length = 100)
    private String department;

    @Column(name = "image_url", length = 512)
    private String imageUrl;

    @Column(length = 500)
    private String bio;

    /** Soft-delete flag — disabled users cannot log in ({@link #isEnabled()}). */
    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    @Column(name = "created_at", updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Automatically updated by Hibernate on every UPDATE statement.
     * No manual {@code @PreUpdate} needed — {@code @UpdateTimestamp} handles it.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // ─── UserDetails contract ──────────────────────────────────────────────────

    /** Returns an empty list — roles/permissions are not yet implemented. */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of();
    }

    /** Spring Security uses this as the credential for authentication. */
    @Override
    public String getPassword() {
        return this.passwordHash;
    }

    /** Spring Security uses the email as the unique username. */
    @Override
    public String getUsername() {
        return this.email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /** A user is enabled as long as the {@code is_active} flag is true. */
    @Override
    public boolean isEnabled() {
        return Boolean.TRUE.equals(this.isActive);
    }
}
